# Netlify Configuration
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Environment variables (set these in Netlify UI)
# VITE_STREAM_API_KEY = your_api_key
# STREAM_API_SECRET = your_api_secret

# Redirect API calls to serverless function
[[redirects]]
  from = "/api/generate-token"
  to = "/.netlify/functions/generate-token"
  status = 200

# SPA fallback - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
